meta:
  seed: 42
  description: "Sensitivity analysis configuration"


model_dir: "ADAM_Brent_L50" # can change to the name of the dir

parameters:
  pairs: 
    - ["gamma", "bar_v"]
    - ["rho", "gamma"]
    - ["kappa", "bar_v"]

  fixed_values:
    rho:  -0.45
    kappa: 1.5
    gamma: 0.4
    bar_v: 0.25
    v0: 0.3
    moneyness: 1.0
    tau: 1.0
    r: 0.025

grid:
  expansion_factor: 1.2
  n_points: 100

error_metric: "abs_diff" # options: abs_diff, rmse, mse, difference
