# Configuration of the synthetic data generated via the Heston COS solver
# Contains:
#   - ranges of the params
#   - grid of strikes K and maturities T
#   - validations (Feller?)

meta:
  name: heston_synth_data
  version: "v1"
  seed: 42

data:
  n_samples: 10000 # start with 10k, then go with 1M
  batch_size: 1024
  heston_params:    # taken from Liu
    rho: [-0.9, 0.0]  # TODO: no positive correlations?
    kappa: [0.0, 3.0]
    gamma: [0.01, 0.8]
    bar_v: [0.01, 0.5]
    v0: [0.05, 0.5]
    fixed: true     # TODO: quitar en un futuro
    sampling:
      n_params_samples: 5 # like Liu aswell
      method: "lhs"

  grid:
  # taken from Liu
    moneyness: [0.6, 1.4] 
    tau: [0.05, 3.0]
    sampling:
      n_params_samples: 100 # TODO: creo que es 5x7
      method: "lhs"

  market:
    r: [0.0, 0.05]
    K: 1                # fixed as Liu
    option_type: "put"  # better for COS 
    sampling:
      n_params_samples: 100 
      method: "lhs"

cos_solver:       # NOT from Liu
  N: 256
  L: 10

brent_iv:         # NOT from Liu
  tol: 1.0e-8
  max_iter: 100
  iv_bounds: [1.0e-4, 3.0]

